apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-analyzer-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: asia-southeast1-docker.pkg.dev/cosmic-shift-470014-h3/article/app-backend:v1
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: production