apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-analyzer-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: asia-southeast1-docker.pkg.dev/cosmic-shift-470014-h3/article/app-frontend:v1
        ports:
        - containerPort: 8501
        env:
        - name: BACKEND_URL
          value: http://article-analyzer-backend
